import { db } from "./index";
import { products } from "./schema";

async function seed() {
  const existing = await db.select().from(products);
  if (existing.length > 0) {
    console.log(`Products already seeded: ${existing.length} products`);
    return;
  }

  const seedProducts = [
    {
      name: "Chiang Mai Botanical Soap",
      category: "soap" as const,
      price: 1299,
      description: "Handcrafted soap infused with wild botanicals from the mountains of Chiang Mai. Features lemongrass, turmeric, and local herbs that gently cleanse while nourishing the skin.",
      shortDesc: "Wild mountain botanicals from Chiang Mai",
      image: "/images/product-01.jpg",
      images: JSON.stringify(["/images/product-07.jpg", "/images/lifestyle-02.jpg"]),
      ingredients: "Olive oil, coconut oil, lemongrass essential oil, turmeric powder, Chiang Mai wild herbs",
      weight: "120g",
      scent: "Lemongrass & Turmeric",
      inStock: 1,
      featured: 1,
    },
    {
      name: "Lemongrass Zest Candle",
      category: "candle" as const,
      price: 1899,
      description: "A revitalizing soy candle with the crisp, citrusy aroma of fresh Thai lemongrass. Hand-poured in a matte ceramic vessel. Burns cleanly for up to 45 hours.",
      shortDesc: "Revitalizing lemongrass soy candle",
      image: "/images/product-02.jpg",
      images: JSON.stringify(["/images/product-06.jpg"]),
      ingredients: "100% natural soy wax, lemongrass essential oil, cotton wick, ceramic vessel",
      burnTime: "45 hours",
      scent: "Lemongrass",
      inStock: 1,
      featured: 1,
    },
    {
      name: "Krabi Coconut Cream Bath Bomb",
      category: "soap" as const,
      price: 899,
      description: "A luxurious bath bomb made with cold-pressed coconut oil from Krabi. Dissolves into creamy, skin-softening foam that hydrates and soothes.",
      shortDesc: "Coconut oil bath bomb from Krabi",
      image: "/images/product-03.jpg",
      images: JSON.stringify(["/images/product-09.jpg"]),
      ingredients: "Sodium bicarbonate, citric acid, Krabi coconut oil, cornstarch, coconut flakes",
      weight: "150g",
      scent: "Coconut & Sea Salt",
      inStock: 1,
      featured: 1,
    },
    {
      name: "Midnight Jasmine Reed Diffuser",
      category: "candle" as const,
      price: 2499,
      description: "An elegant reed diffuser that fills your space with the intoxicating scent of Thai jasmine blossoms. The amber glass vessel is hand-blown by artisans in Bangkok.",
      shortDesc: "Thai jasmine reed diffuser",
      image: "/images/product-04.jpg",
      images: JSON.stringify(["/images/lifestyle-01.jpg"]),
      ingredients: "Jasmine essential oil, natural carrier oil, hand-blown amber glass, natural rattan reeds",
      burnTime: "3 months",
      scent: "Thai Jasmine",
      inStock: 1,
      featured: 1,
    },
    {
      name: "Rice Milk & Honey Soap",
      category: "soap" as const,
      price: 999,
      description: "A gentle, moisturizing soap made with organic jasmine rice milk and raw Thai honey. Rich in vitamins and amino acids, it soothes sensitive skin.",
      shortDesc: "Gentle rice milk and honey soap",
      image: "/images/product-05.jpg",
      images: JSON.stringify(["/images/product-01.jpg"]),
      ingredients: "Rice milk, Thai honey, shea butter, coconut oil, olive oil, vitamin E",
      weight: "110g",
      scent: "Honey & Rice Milk",
      inStock: 1,
      featured: 0,
    },
    {
      name: "Sandalwood Meditation Candle",
      category: "candle" as const,
      price: 2199,
      description: "A deeply grounding candle with the warm, woody scent of Thai sandalwood. Perfect for meditation and creating a calming atmosphere.",
      shortDesc: "Grounding sandalwood candle",
      image: "/images/product-06.jpg",
      images: JSON.stringify(["/images/product-02.jpg"]),
      ingredients: "Soy wax, sandalwood essential oil, cotton wick, stoneware vessel",
      burnTime: "50 hours",
      scent: "Sandalwood",
      inStock: 1,
      featured: 0,
    },
    {
      name: "Botanical Sampler Set",
      category: "gift_set" as const,
      price: 3499,
      description: "A curated collection of five mini soap bars, each featuring a different Thai botanical. Beautifully packaged in a handmade kraft box.",
      shortDesc: "Five mini soaps in a gift box",
      image: "/images/product-07.jpg",
      images: JSON.stringify(["/images/product-08.jpg"]),
      ingredients: "Varies by bar - all natural oils and botanical extracts",
      weight: "5 x 40g",
      scent: "Assorted Botanicals",
      inStock: 1,
      featured: 1,
    },
    {
      name: "Spa Retreat Gift Set",
      category: "gift_set" as const,
      price: 4999,
      description: "The ultimate Thai spa experience in a box. Includes a full-size botanical soap, a soy candle, a coconut bath bomb, and a jasmine reed diffuser sample.",
      shortDesc: "Complete Thai spa experience",
      image: "/images/product-08.jpg",
      images: JSON.stringify(["/images/product-07.jpg"]),
      ingredients: "See individual products",
      weight: "800g total",
      scent: "Assorted",
      inStock: 1,
      featured: 1,
    },
    {
      name: "Pandan Leaf & Lime Soap",
      category: "soap" as const,
      price: 1199,
      description: "A refreshing soap combining the grassy sweetness of pandan leaves with zesty Thai lime. The natural green color comes from fresh pandan extract.",
      shortDesc: "Fresh pandan and lime soap",
      image: "/images/product-09.jpg",
      images: JSON.stringify(["/images/product-03.jpg"]),
      ingredients: "Coconut oil, olive oil, pandan extract, lime essential oil, shea butter",
      weight: "120g",
      scent: "Pandan & Lime",
      inStock: 1,
      featured: 0,
    },
    {
      name: "Orchid & Vanilla Candle",
      category: "candle" as const,
      price: 1999,
      description: "A romantic candle blending the exotic floral notes of Thai orchids with creamy vanilla. Hand-poured in a frosted glass vessel.",
      shortDesc: "Orchid and vanilla soy candle",
      image: "/images/lifestyle-02.jpg",
      images: JSON.stringify(["/images/product-04.jpg"]),
      ingredients: "Soy wax, orchid fragrance oil, vanilla essential oil, cotton wick",
      burnTime: "40 hours",
      scent: "Orchid & Vanilla",
      inStock: 1,
      featured: 0,
    },
    {
      name: "Charcoal & Tea Tree Detox Soap",
      category: "soap" as const,
      price: 1399,
      description: "A deep-cleansing soap featuring activated bamboo charcoal and tea tree oil. Ideal for oily and acne-prone skin.",
      shortDesc: "Detoxifying charcoal soap",
      image: "/images/product-01.jpg",
      images: JSON.stringify(["/images/product-05.jpg"]),
      ingredients: "Activated bamboo charcoal, tea tree oil, coconut oil, olive oil, shea butter",
      weight: "130g",
      scent: "Tea Tree",
      inStock: 1,
      featured: 0,
    },
    {
      name: "Mango & Sticky Rice Candle",
      category: "candle" as const,
      price: 1799,
      description: "A deliciously scented candle inspired by Thailand's beloved mango sticky rice dessert. Sweet mango blends with creamy coconut.",
      shortDesc: "Mango sticky rice inspired candle",
      image: "/images/product-03.jpg",
      images: JSON.stringify(["/images/product-06.jpg"]),
      ingredients: "Soy wax, mango fragrance, coconut oil, rice absolute, cotton wick",
      burnTime: "42 hours",
      scent: "Mango & Coconut",
      inStock: 1,
      featured: 0,
    },
    {
      name: "Rose & Goat Milk Soap",
      category: "soap" as const,
      price: 1499,
      description: "An ultra-luxurious soap combining Bulgarian rose essential oil with creamy Thai goat milk. Leaves skin silky smooth.",
      shortDesc: "Luxurious rose and goat milk soap",
      image: "/images/product-05.jpg",
      images: JSON.stringify(["/images/product-02.jpg"]),
      ingredients: "Thai goat milk, rose essential oil, dried rose petals, olive oil, coconut oil",
      weight: "115g",
      scent: "Bulgarian Rose",
      inStock: 1,
      featured: 0,
    },
    {
      name: "Tropical Paradise Gift Set",
      category: "gift_set" as const,
      price: 5999,
      description: "A lavish gift set featuring our most popular tropical scents. All packaged in a handwoven bamboo basket.",
      shortDesc: "Tropical scent collection",
      image: "/images/product-07.jpg",
      images: JSON.stringify(["/images/product-08.jpg"]),
      ingredients: "See individual products",
      weight: "1.2kg total",
      scent: "Tropical Assortment",
      inStock: 1,
      featured: 0,
    },
    {
      name: "Ylang-Ylang & Patchouli Candle",
      category: "candle" as const,
      price: 2099,
      description: "A sensual, exotic candle blending the sweet floral notes of ylang-ylang with earthy patchouli.",
      shortDesc: "Sensual ylang-ylang candle",
      image: "/images/product-04.jpg",
      images: JSON.stringify(["/images/lifestyle-01.jpg"]),
      ingredients: "Soy wax, ylang-ylang essential oil, patchouli essential oil, cotton wick",
      burnTime: "48 hours",
      scent: "Ylang-Ylang & Patchouli",
      inStock: 1,
      featured: 0,
    },
  ];

  await db.insert(products).values(seedProducts);
  console.log(`Seeded ${seedProducts.length} products successfully!`);
}

seed().catch(console.error);
